### ISSUE TITLE
Pull all of the apps in the scripts directory into a single command line interface

### ISSUE THREAD

**Issue by mfitz** [arup-group/genet#127]
GeNet has a bunch of useful python applications in the `scripts` directory to perform tasks such as validating or simplifying a network, or adding elevation and slope data to a network. It would be good to pull all of these different apps into a single, discoverable CLI so that we could issue commands such as `genet network simplify`, `genet network validate` or `genet network add-link-slopes`. The CLI should be discoverable, enabling commands such as `genet --help`, `genet network --help` or `genet network simplify --help`.

**Comment by KasiaKoz** [comment]
We need to make sure that the recent summary stats: https://github.com/arup-group/genet/issues/135 are included in the cli

**Comment by KasiaKoz** [comment]
Done in https://github.com/arup-group/genet/pull/194
