### ISSUE TITLE
Summary Stats 

### ISSUE THREAD

**Issue by KasiaKoz** [arup-group/genet#135]
Methods to print to console and save to file (via standard outputs) summary statistics about the entire network and schedule.

Let's discuss what statistics should be included.

I envision a method `summary` for both network and schedule; something like this within network:

```python
def summary(self):
   module.summarise_network(self)
   if self.schedule:
       self.schedule.summary()
```

**Comment by KasiaKoz** [comment]
network and schedule have a print methods that show number of links, nodes and services and stops respectively:

```
Graph info: Name: Network graph
Type: MultiDiGraph
Number of nodes: 387573
Number of edges: 883961
Average in degree:   2.2808
Average out degree:   2.2808 
Schedule info: Schedule:
Number of services: 1013
Number of routes: 1398
Number of stops: 14142
```

might be good to report a split by mode perhaps, e.g. `n` bus services (stops dont really have modes, but you can link them up with the routes that use them and those have modes (confer recent multimodal access/egress work)

**Comment by KasiaKoz** [comment]
a simple summary of all modes on the links, and all PT modes

**Comment by KasiaKoz** [comment]
`X.link/node/stop/route/service_attribute_summary(data=True)` gives the data schema, all attributes and additional (nested) attributes for link/node/stop/route/service objects belonging to network/schedule, and an example of 5 values under that attribute, but the underlying method that generates this can be configured differently --- it shows unique values, in some cases there are many, e.g. osm IDs so we limited them to 5, but in some cases, like modes, it would make sense to show all.

**Comment by KasiaKoz** [comment]
stats about headways might be useful (if they are not being saved with standard outputs already) 
https://github.com/arup-group/genet/blob/main/genet/schedule_elements.py#L1526

**Comment by fredshone** [comment]
two cases come up recently:
1) people asking for summary stats of network and schedules, often split by mode. I think well covered above.
2) me getting caught out by the precise naming of stop attributes as required for the intermodal access/egress stuff

pam and mc have summary cli commands which stdout out everything that might be useful, the idea being that someone will read and copy/paste only what they need. So the more the merrier i guess - provided it is clearly presented

**Comment by ana-kop** [comment]
@KasiaKoz @fredshone I have created a method that I think includes most of the things you mention - here is what it gives when used on the TE network + schedule:
```
{'network_graph_info': {'Number of network links': 447610,
  'Number of network nodes': 985170},
 'modes': {'Modes on network links': {'artificial',
   'bike',
   'bus',
   'car',
   'ferry',
   'gondola',
   'rail',
   'stopFacilityLink',
   'subway',
   'tram',
   'walk'},
  'Number of links by mode': {'stopFacilityLink': 17415,
   'bus': 171946,
   'ferry': 17427,
   'bike': 813950,
   'car': 964741,
   'gondola': 17415,
   'artificial': 17415,
   'rail': 17967,
   'walk': 858460,
   'tram': 17419,
   'subway': 17460},
  'Modes in schedule': {'bus', 'ferry', 'rail', 'subway', 'tram'},
  'Services by mode': {'bus': 1165,
   'rail': 174,
   'tram': 1,
   'ferry': 4,
   'subway': 6}},
 'osm_highway_tags': {'Number of links by tag': {'unclassified': 83345,
   'tertiary_link': 93,
   'proposed': 2,
   'tertiary': 97991,
   'service': 350477,
   'footway': 224,
   'primary_link': 819,
   'secondary': 36269,
   'secondary_link': 75,
   'trunk': 66798,
   'cycleway': 1577,
   'living_street': 3410,
   'path': 34,
   'motorway': 2085,
   'bridleway': 54,
   'motorway_link': 2123,
   'primary': 38304,
   'steps': 2,
   'pedestrian': 34,
   'track': 90,
   'construction': 2,
   'trunk_link': 7865,
   'residential': 288954}},
 'schedule_info': {'Number of services': 1350,
  'Number of routes': 4685,
  'Number of stops:': 20198}}
```

Does this seem like enough?

**Comment by ana-kop** [comment]
@zishushu

**Comment by zishushu** [comment]
Re schedule info - is it possible to break down no.stops/stations by mode?

**Comment by ana-kop** [comment]
Yeah sure I can do that @zishushu

**Comment by fredshone** [comment]
can you add the schedule stop attributes, eg bikeAccess = "True". I realise you will need to ignore the link ids

**Comment by fredshone** [comment]
how will this method be accessed? CLI or in a notebook?

**Comment by ana-kop** [comment]
@fredshone sure, you mean a count of the stops with that tag?

This is a method for the `network` object, so you need to load in a network to use it; I will also add it to the standard outputs to save the report - see the PR [here](https://github.com/arup-group/genet/pull/136)

**Comment by KasiaKoz** [comment]
@fredshone there is no command line interface to genet right now, that's a separate issue: https://github.com/arup-group/genet/issues/127. You can access it via a python interface of your choice, a notebook, ipython shell or script.
I made a note in the aforementioned issue that summary stats be exposed in the cli.
