### ISSUE TITLE
need check for np.inf linkspeeds

### ISSUE THREAD

**Issue by fredshone** [arup-group/genet#19]
`"inf"` link speeds cause matsim to fail, eg:

```<link id="pt_150042002011" from="pt_150042002011" to="pt_150042002011" freespeed="inf" capacity="9999.0" permlanes="1.0" oneway="1" modes="bus,artificial,stopfacilitylink" length="1.0"/>```

**Comment by KasiaKoz** [comment]
https://arupdigital.atlassian.net/browse/LAB-588
