### ISSUE TITLE
BUG: `route` is both a method and an attribute of `Route`

### ISSUE THREAD

**Issue by brynpickering** [arup-group/genet#228]
`Route.route` is both a list attribute and a method that takes a route ID returns `self` if the input route ID == `self.id`.

**Comment by KasiaKoz** [comment]
I think we should rename the `route` attribute to `network_route`, it's very confusing (we inherited that from matsim)

**Comment by brynpickering** [comment]
Or something like `route_links` or simply `links`? The attribute is a list of link IDs that define the route, so it would be good if it reflects that in its name.

**Comment by brynpickering** [comment]
We went with `network_links` in the rename.
